Catching TransactionSystemException sometimes thrown on Postgres in serializable mode
org.springframework.transaction.TransactionSystemException: JDBC commit failed; nested exception is org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during commit attempt.
  Hint: The transaction might succeed if retried.

https://stackoverflow.com/questions/42288808/why-does-postgresql-serializable-transaction-think-this-as-conflict/42303225